export const JOB_LIST_REQUEST = 'JOB_LIST_REQUEST'
export const JOB_LIST_SUCCESS = 'JOB_LIST_SUCCESS'
export const JOB_LIST_FAIL = 'JOB_LIST_FAIL'

export const JOB_DETAIL_REQUEST = 'JOB_DETAIL_REQUEST'
export const JOB_DETAIL_SUCCESS = 'JOB_DETAIL_SUCCESS'
export const JOB_DETAIL_FAIL = 'JOB_DETAIL_FAIL'

export const JOB_DELETE_REQUEST = 'JOB_DELETE_REQUEST'
export const JOB_DELETE_SUCCESS = 'JOB_DELETE_SUCCESS'
export const JOB_DELETE_FAIL = 'JOB_DELETE_FAIL'

export const JOB_CREATE_REQUEST = 'JOB_CREATE_REQUEST'
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS'
export const JOB_CREATE_FAIL = 'JOB_CREATE_FAIL'
export const JOB_CREATE_RESET = 'JOB_CREATE_RESET'

export const JOB_UPDATE_REQUEST = 'JOB_UPDATE_REQUEST'
export const JOB_UPDATE_SUCCESS = 'JOB_UPDATE_SUCCESS'
export const JOB_UPDATE_FAIL = 'JOB_UPDATE_FAIL'
export const JOB_UPDATE_RESET = 'JOB_UPDATE_RESET'

export const APPLICANT_CREATE_REQUEST = 'APPLICANT_CREATE_REQUEST'
export const APPLICANT_CREATE_SUCCESS = 'APPLICANT_CREATE_SUCCESS'
export const APPLICANT_CREATE_FAIL = 'APPLICANT_CREATE_FAIL'

export const APPLICANT_LIST_REQUEST = 'APPLICANT_LIST_REQUEST'
export const APPLICANT_LIST_SUCCESS = 'APPLICANT_LIST_SUCCESS'
export const APPLICANT_LIST_FAIL = 'APPLICANT_LIST_FAIL'
